import { Nunito } from 'next/font/google'
import "./globals.css";

export const metadata = {
  title: "Pide Comida a Domicilio y mucho más - Rappi Colombia",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets:["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
